[package]
name = "linux_rig"
version = "0.1.0"
edition = "2021"

[dependencies]
# tarpc = { version = "0.33", features = ["full"] }
# tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
# futures = "0.3"
# anyhow = "1"

[lib]
name = "rig_info"
path = "src/lib.rs"
